### ISSUE TITLE
INT too large error

### ISSUE THREAD

**Issue by daniviga** [gem/oq-installers#5]
Sometime an error about INT is triggered:

```
[2016-02-19 12:19:02,217 #1 INFO] classical  93%
[2016-02-19 12:19:03,259 #1 INFO] classical 100%
[2016-02-19 12:19:03,259 #1 INFO] Received 25.47 MB of data, maximum per task 1
59 MB
[2016-02-19 12:19:03,869 #1 INFO] Total time spent: 205.950999975 s
[2016-02-19 12:19:03,869 #1 INFO] Memory allocated: 6.78 MB
See the output with hdfview C:\Documents and Settings\utente/oqdata\calc_1.hdf5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Programmi\File comuni\Python\2.7\lib\threading.py", line 801, in __b
otstrap_inner
    self.run()
  File "C:\Programmi\File comuni\Python\2.7\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Programmi\OpenQuake Engine Lite\pkgs\concurrent\futures\process.py",
line 235, in _queue_management_worker
    p.join(sys.maxint)
  File "C:\Programmi\File comuni\Python\2.7\lib\multiprocessing\process.py", li
e 145, in join
    res = self._popen.wait(timeout)
  File "C:\Programmi\File comuni\Python\2.7\lib\multiprocessing\forking.py", li
e 297, in wait
    res = _subprocess.WaitForSingleObject(int(self._handle), msecs)
OverflowError: Python int too large to convert to C long
```

**Comment by daniviga** [comment]
Has been fixed using `futures==2.1.6`
