### ISSUE TITLE
Unicode issues on Windows

### ISSUE THREAD

**Issue by daniviga** [gem/oq-installers#9]
`C:\Program Files (x86)\OpenQuake Engine Lite>oq-lite.py show contents 1`

``` python
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenQuake Engine Lite\oq-lite.py", line 32, in <module>
    oq_lite()
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\commands\__main__.py", line 33, in oq_lite
    parser.callfunc()
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\sap.py", line 170, in callfunc
    return self.func(**vars(namespace))
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\sap.py", line 204, in main
    return func(**kw)
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\commands\show.py", line 99, in show
    print(datastore.view(what, ds))
  File "C:\Program Files (x86)\Common Files\Python\2.7\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014' in position 53: character maps to <undefined>
```

**Comment by daniviga** [comment]
I've been able to reproduce the error using the `AreaSourceClassicalPSHA` demo

**Comment by daniviga** [comment]
Not an issue of the Windows installer should be fixed in `oq-risklib`. See https://github.com/gem/oq-risklib/issues/737
